[package]
name = "nname"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = "z"
debug = false
lto = "thin"
debug-assertions = false
codegen-units = 1
panic = "abort"
strip = true

[dependencies]
clap = { version = "4.5", features = ["derive"] }
